"""Produce a CycloneDX 1.5 SBOM from the resolved lock file.

The lock is the right source. An SBOM generated by introspecting whatever happens to be
installed describes one machine at one moment; one generated from `uv.lock` describes the
dependency set that will actually be resolved for a release, is byte-identical on every
machine, and can be produced without a network call or an environment.

Scope defaults to the runtime dependency closure. `--include-dev` widens it to the
development group, which is useful for auditing the toolchain but is not what ships.

    uv run python scripts/build_sbom.py --output dist/sbom.cdx.json

`uv export --format cyclonedx1.5` is the intended independent cross-check while that
exporter remains preview. Two tools that agree are evidence; one tool is an assertion.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import tomllib
from pathlib import Path
from typing import Any, Final

from _gate import REPO_ROOT, GateResult, failed, passed, report

GATE: Final[str] = "G11 SBOM"

LOCK_PATH = REPO_ROOT / "uv.lock"
PYPROJECT_PATH = REPO_ROOT / "pyproject.toml"

#: CycloneDX spec this document targets. Pinned, because a consumer validates against it.
SPEC_VERSION: Final[str] = "1.5"


def _load_lock() -> dict[str, Any]:
    with LOCK_PATH.open("rb") as handle:
        data: dict[str, Any] = tomllib.load(handle)
    return data


def _load_project() -> dict[str, Any]:
    with PYPROJECT_PATH.open("rb") as handle:
        data: dict[str, Any] = tomllib.load(handle)
    project: dict[str, Any] = data["project"]
    return project


def _requirement_name(requirement: str) -> str:
    for separator in ("[", "<", ">", "=", "!", "~", ";", " "):
        requirement = requirement.split(separator, 1)[0]
    return requirement.strip().lower().replace("_", "-")


def _packages(lock: dict[str, Any]) -> dict[str, dict[str, Any]]:
    packages: dict[str, dict[str, Any]] = {}
    for entry in lock.get("package", []):
        name = str(entry.get("name", "")).lower().replace("_", "-")
        if name:
            packages[name] = entry
    return packages


def _closure(roots: set[str], packages: dict[str, dict[str, Any]]) -> set[str]:
    """Transitive dependency closure, so a vulnerable transitive package is in the SBOM."""
    seen: set[str] = set()
    frontier = list(roots)
    while frontier:
        name = frontier.pop()
        if name in seen or name not in packages:
            continue
        seen.add(name)
        for dependency in packages[name].get("dependencies", []):
            child = str(dependency.get("name", "")).lower().replace("_", "-")
            if child and child not in seen:
                frontier.append(child)
    return seen


def _component(entry: dict[str, Any]) -> dict[str, Any]:
    name = str(entry["name"])
    version = str(entry.get("version", ""))
    component: dict[str, Any] = {
        "type": "library",
        "bom-ref": f"pkg:pypi/{name}@{version}",
        "name": name,
        "version": version,
        "purl": f"pkg:pypi/{name}@{version}",
    }

    hashes = []
    for artifact in [entry.get("sdist"), *(entry.get("wheels", []) or ())]:
        if not isinstance(artifact, dict):
            continue
        digest = artifact.get("hash")
        if isinstance(digest, str) and digest.startswith("sha256:"):
            hashes.append({"alg": "SHA-256", "content": digest.split(":", 1)[1]})
    if hashes:
        # Deterministic order: an SBOM that reorders between runs cannot be diffed.
        component["hashes"] = sorted(hashes, key=lambda item: str(item["content"]))
    return component


def build(*, include_dev: bool) -> dict[str, Any]:
    lock = _load_lock()
    project = _load_project()
    packages = _packages(lock)

    roots = {_requirement_name(item) for item in project.get("dependencies", [])}
    if include_dev:
        with PYPROJECT_PATH.open("rb") as handle:
            groups = tomllib.load(handle).get("dependency-groups", {})
        for entries in groups.values():
            roots |= {_requirement_name(str(item)) for item in entries}

    selected = sorted(_closure(roots, packages))
    components = [_component(packages[name]) for name in selected if name in packages]

    return {
        "bomFormat": "CycloneDX",
        "specVersion": SPEC_VERSION,
        "version": 1,
        "metadata": {
            "component": {
                "type": "application",
                "bom-ref": f"pkg:pypi/{project['name']}@{project['version']}",
                "name": project["name"],
                "version": project["version"],
                "description": project.get("description", ""),
            },
            "properties": [
                {"name": "prism:source", "value": "uv.lock"},
                {"name": "prism:scope", "value": "runtime+dev" if include_dev else "runtime"},
            ],
        },
        "components": components,
    }


def run(*, include_dev: bool = False, output: Path | None = None) -> GateResult:
    if not LOCK_PATH.is_file():
        return failed(GATE, [f"missing lock file: {LOCK_PATH.name}"])

    document = build(include_dev=include_dev)
    rendered = json.dumps(document, indent=2, sort_keys=True) + "\n"

    findings: list[str] = []
    if not document["components"]:
        findings.append("the SBOM resolved no components, which cannot be correct")

    if output is not None:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(rendered, encoding="utf-8")

    detail = {
        "components": len(document["components"]),
        "scope": "runtime+dev" if include_dev else "runtime",
        "digest": "sha256:" + hashlib.sha256(rendered.encode("utf-8")).hexdigest(),
        "output": str(output) if output else "(not written)",
    }
    if findings:
        return failed(GATE, findings, **detail)
    return passed(GATE, **detail)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", default=None, help="write the SBOM to this path")
    parser.add_argument("--include-dev", action="store_true", help="include the dev group")
    parser.add_argument("--json", action="store_true", help="emit a machine-readable result")
    args = parser.parse_args()
    output = Path(args.output) if args.output else None
    return report(run(include_dev=args.include_dev, output=output), as_json=args.json)


if __name__ == "__main__":
    raise SystemExit(main())
